### ISSUE TITLE
    java.lang.IllegalStateException: DataBindingUtil.inflate(…onsent, container, false) must not be null

### ISSUE THREAD

**Issue by Photogad** [DavidEdwards/GDPRConsent#9]
java.lang.IllegalStateException: DataBindingUtil.inflate(…onsent, container, false) must not be null
        at dae.gdprconsent.ConsentRequestDetailFragment.onCreateView(ConsentRequestDetailFragment.kt:46)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:739)
        at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:809)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2422)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1504)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
05-28 03:58:52.178 15366-15366/com.pa.modelreleaseapp E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-28 03:58:52.188 15366-15366/com.pa.modelreleaseapp E/UncaughtException: java.lang.IllegalStateException: DataBindingUtil.inflate(…onsent, container, false) must not be null
        at dae.gdprconsent.ConsentRequestDetailFragment.onCreateView(ConsentRequestDetailFragment.kt:46)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:739)
        at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:809)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2422)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1504)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Photogad** [comment]
I added all dependencies and plugins mentioned in the readme.md, exactly.

I try to display the GDPR by calling

`GDPRConsent();`

which opens my method:

```
    public void GDPRConsent() {


        AlertDialog.Builder builder;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            builder = new AlertDialog.Builder(this, android.R.style.Theme_Material_Dialog_Alert);
        } else {
            builder = new AlertDialog.Builder(this);
        }
        builder.setTitle("GDPR Consent")
                .setMessage("We apologize for this, but due to new European laws enacted on May 25th 2018, you must go through a lengthy consent screen to enable app features before using the app. You can read the details on each item on the next screens, and you must tap on the consent toggle at the top of the screen to enable each one before using the app.")
                .setPositiveButton(android.R.string.yes, new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int which) {
                        // continue with delete
                    }
                })
                .setIcon(android.R.drawable.ic_dialog_alert)
                .show();

        ArrayList<ConsentRequest> list = new ArrayList<>();

        list.add(new ConsentRequest(
                "AGE_16",
                false,
                false,
                true,
                "2018-05-09",
                "How old are you?",
                "Age",
                "https://gdpr-info.eu/art-8-gdpr/",
                "You must be at least 16 years of age to use this App.",
                "Due to European regulations and laws, you must be at least 16 years of age to use this App and you must verify it by tapping the consent option at the top of this screen."
        ));

        list.add(new ConsentRequest(
                "BASIC_APP",
                false,
                false,
                true,
                "2018-05-09",
                "Basic functions",
                "Application",
                "http://example.com/gdpr",
                "We store your E-mail address, password, billing address, ..., on our servers.",
                "We need this information to perform the basic functionality of this App. Fill this section with more information about how each item is specific required."
        ));

        list.add(new ConsentRequest(
                "FIREBASE_STATISTICS",
                false,
                false,
                false,
                "2018-05-08",
                "Statistics",
                "Analytics",
                "https://firebase.google.com/support/privacy/",
                "Firebase analytics are used so we can see how users are using our app, and what we can do to make the app better for everyone. We do not use the information for any nefarious purposes, and your information is anonymous. We highly recommend enabling this option so that we can improve the app.",
                "Firebase stores your Mobile Ad ID, Android ID, Instance ID and Analytics App Instance IDs. ID specific data is deleted after 60 days."
        ));

        list.add(new ConsentRequest(
                "FIREBASE_CRASH",
                false,
                false,
                false,
                "2018-05-07",
                "Crash reporting",
                "Analytics",
                "https://firebase.google.com/support/privacy",
                "We need this to learn how and when crashes are happening in the app, so we can promptly fix them. We do not use the information for any nefarious purposes, and your information is anonymous. We highly recommend enabling this option so we can fix bugs and crashes in the app to make it better.",
                "Firebase stores your Instance ID and crash traces. Crash traces are deleted after 180 days."
        ));

        if(ConsentHelper.hasNewOrRequired(this, list)) {
            ConsentHelper.showGdprOnlyNew(this, RC_CONSENT, list);
        }
    }
```


I also added the following:

```
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        //// for GDPR consent
        if(requestCode == RC_CONSENT) {
            if(resultCode == Activity.RESULT_OK) {
                // User passed through the consent system completely

                boolean consentChanged = data.getExtras() != null && data.getExtras().getBoolean(Constants.KEY_CONSENT_CHANGED);
                if(consentChanged) {
                    Intent intent = new Intent(this, MainActivity.class);
                    PendingIntent pending = PendingIntent.getActivity(this, RC_RESTART, intent, PendingIntent.FLAG_CANCEL_CURRENT);
                    AlarmManager alarmManager = (AlarmManager) this.getSystemService(Context.ALARM_SERVICE);
                    if (alarmManager != null) {
                        alarmManager.set(AlarmManager.RTC, System.currentTimeMillis() + 100, pending);
                    }
                    finish();
                    System.exit(0);
                }

                Log.v("CONSENT", "Consent for basic App functions: "+ConsentHelper.hasConsent("BASIC_APP"));
                Log.v("CONSENT", "Consent for statistics collection: "+ConsentHelper.hasConsent("FIREBASE_STATISTICS"));
                Log.v("CONSENT", "Consent for crash reporting: "+ConsentHelper.hasConsent("FIREBASE_CRASH"));
            } else {
                // User closed the consent system without progressing through it
                finish();
            }
        }

    }
```

**Comment by DavidEdwards** [comment]
Do you perhaps have a layout that goes by one of these names?

![image](https://user-images.githubusercontent.com/1585923/40602687-cd825258-6259-11e8-8f6a-0cf7277bdf15.png)

If a layout error comes from my code, the odds are that you are inadvertently overriding a layout file.

**Comment by DavidEdwards** [comment]
If that isn't the case, you can also try using this:

implementation 'com.github.DavidEdwards:GDPRConsent:master-SNAPSHOT'

That includes the latest (non-public) change that changes this inflation line to use more recommended code.

Edit: or the latest version that also includes this change.

implementation 'com.github.DavidEdwards:GDPRConsent:0.9.5'

**Comment by Photogad** [comment]
I have an activity_gdpr.xml but not an activity_gdpr_main.xml, and no fragment_gdpr_consent.

I'll try with the 0.9.5 version when I get back home tomorrow, right now I was using the 0.9.4 version

**Comment by Photogad** [comment]
update: tried with 0.9.5 but still getting same error.

is there something wrong with the code i'm using above to display it?

**Comment by Photogad** [comment]
nevermind, got it working. i missed where you said to use the gradle alpha version, i was using the non-alpha version of gradle and that was causing the crash.

**Comment by DavidEdwards** [comment]
Ah ha, glad you solved it!
